<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: sans-serif; font-size: 12px; color: #111827; }
        h1 { font-size: 20px; margin-bottom: 4px; }
        h2 { font-size: 15px; margin-top: 24px; margin-bottom: 8px; border-bottom: 1px solid #d1d5db; padding-bottom: 4px; }
        .meta { color: #6b7280; margin-bottom: 16px; }
        .sites { margin-bottom: 8px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 12px; }
        th, td { text-align: left; padding: 6px 8px; border: 1px solid #e5e7eb; }
        th { background: #f3f4f6; }
        .notice { color: #b45309; background: #fffbeb; border: 1px solid #fde68a; padding: 8px; margin-bottom: 12px; }
        .muted { color: #6b7280; }
    </style>
</head>
<body>
    <h1>Website Report</h1>
    <div class="meta">
        Generated by {{ $user->name }} on {{ $generatedAt->format('Y-m-d H:i') }}<br>
        Period: {{ $report['period']['from'] }} to {{ $report['period']['to'] }}
    </div>

    @if ($report['marketing'])
        <h2>Marketing</h2>
        <div class="sites">
            <strong>Sites:</strong> {{ implode(', ', array_column($report['marketing']['websites'], 'name')) }}
        </div>

        @if ($report['marketing']['error'])
            <div class="notice">{{ $report['marketing']['error'] }}</div>
        @else
            <table>
                <thead>
                    <tr><th>Source</th><th>Metric</th><th>Value</th></tr>
                </thead>
                <tbody>
                    @foreach (['ga4' => 'GA4', 'gsc' => 'Search Console', 'ahrefs' => 'Ahrefs'] as $key => $label)
                        @php $source = $report['marketing'][$key]; @endphp
                        @if ($source['status'] === 'ok')
                            @foreach ($source['kpis'] as $metric => $kpi)
                                <tr>
                                    <td>{{ $label }}</td>
                                    <td>{{ ucwords(str_replace('_', ' ', $metric)) }}</td>
                                    <td>{{ $kpi['current'] === null ? '—' : (is_float($kpi['current']) ? number_format($kpi['current'], 2) : $kpi['current']) }}</td>
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td>{{ $label }}</td>
                                <td colspan="2" class="muted">{{ $source['status'] === 'missing' ? 'No data for this period.' : ('Unavailable: '.$source['error']) }}</td>
                            </tr>
                        @endif
                    @endforeach
                </tbody>
            </table>
        @endif
    @endif

    @if ($report['customer_service'])
        <h2>Customer Service</h2>
        <div class="sites">
            <strong>Sites:</strong> {{ implode(', ', array_column($report['customer_service']['websites'], 'name')) }}
        </div>

        @if ($report['customer_service']['status'] === 'ok')
            <table>
                <thead>
                    <tr><th>Metric</th><th>Value</th></tr>
                </thead>
                <tbody>
                    @foreach ($report['customer_service']['data'] as $metric => $value)
                        <tr><td>{{ ucwords(str_replace('_', ' ', $metric)) }}</td><td>{{ $value }}</td></tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <div class="notice">{{ $report['customer_service']['error'] }}</div>
        @endif
    @endif

    @if (! $report['marketing'] && ! $report['customer_service'])
        <p class="muted">No assigned websites were selected for this report.</p>
    @endif
</body>
</html>
